name: pr-validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, assigned, unassigned, labeled, unlabeled]
  workflow_dispatch:

jobs:
  require-assignment-and-linked-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR has assignee
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr.assignees || pr.assignees.length === 0) {
              core.setFailed('PR must have at least one assignee.');
            }
      - name: Require linked issue (mention or closing keywords)
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = (pr.body || '') + '\n' + (pr.title || '');
            const closeRegex = /(close[sd]?|fixe[sd]?|resolve[sd]?)\s+#(\d+)/ig;
            const mentionRegex = /#(\d+)/g;
            const numbers = new Set();
            let m;
            while ((m = closeRegex.exec(body)) !== null) {
              numbers.add(parseInt(m[2], 10));
            }
            while ((m = mentionRegex.exec(body)) !== null) {
              numbers.add(parseInt(m[1], 10));
            }
            if (numbers.size === 0) {
              core.setFailed('PR must link an issue (e.g., add "#123" in the title/body or use closing keywords).');
            }
            core.exportVariable('LINKED_ISSUES', Array.from(numbers).join(','));
      - name: Check linked issues are assigned
        uses: actions/github-script@v7
        with:
          script: |
            const env = process.env;
            const nums = (env.LINKED_ISSUES || '').split(',').filter(Boolean).map(n => parseInt(n, 10));
            const numbers = new Set(nums);
            for (const number of numbers) {
              const { data: issue } = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
              });
              if (!issue.assignees || issue.assignees.length === 0) {
                core.setFailed(`Linked issue #${number} has no assignee.`);
              }
            }
      - name: Require at least one reviewer
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const reviewers = (pr.requested_reviewers || []).map(r => r.login);
            if (!reviewers || reviewers.length === 0) {
              core.setFailed('PR must have at least one requested reviewer.');
            }
            for (const number of found) {
              const { data: issue } = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
              });
              if (!issue.assignees || issue.assignees.length === 0) {
                core.setFailed(`Linked issue #${number} has no assignee.`);
              }
            }
